version: 2.0
jobs: # 1回の実行の基本作業単位
  build: # Workflows を使用しない実行では、エントリポイントとして `build` ジョブが必要
    docker: # Dockerでステップを実行
      - image: circleci/python:3.6.3
    steps:
      - checkout # プロジェクトのソースコードをworking_directoryで指定されたパスにチェックアウト
      - run:
          name: install dependencies
          command: | # 仮想環境作成, 仮想環境をアクティベート, pip install
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run test
          command: |
            source .venv/bin/activate
            pytest tests
